/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PAccordion: typeof import('primevue/accordion')['default']
    PAccordionContent: typeof import('primevue/accordioncontent')['default']
    PAccordionHeader: typeof import('primevue/accordionheader')['default']
    PAccordionPanel: typeof import('primevue/accordionpanel')['default']
    PAvatar: typeof import('primevue/avatar')['default']
    PButton: typeof import('primevue/button')['default']
    PCarousel: typeof import('primevue/carousel')['default']
    PCheckbox: typeof import('primevue/checkbox')['default']
    PChip: typeof import('primevue/chip')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PDivider: typeof import('primevue/divider')['default']
    PDynamicDialog: typeof import('primevue/dynamicdialog')['default']
    PGalleria: typeof import('primevue/galleria')['default']
    PIconField: typeof import('primevue/iconfield')['default']
    PInputIcon: typeof import('primevue/inputicon')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    POverlayBadge: typeof import('primevue/overlaybadge')['default']
    PPaginator: typeof import('primevue/paginator')['default']
    PPassword: typeof import('primevue/password')['default']
    PRadioButton: typeof import('primevue/radiobutton')['default']
    PScrollPanel: typeof import('primevue/scrollpanel')['default']
    PSelect: typeof import('primevue/select')['default']
    PSelectButton: typeof import('primevue/selectbutton')['default']
    PTab: typeof import('primevue/tab')['default']
    PTabList: typeof import('primevue/tablist')['default']
    PTabPanel: typeof import('primevue/tabpanel')['default']
    PTabPanels: typeof import('primevue/tabpanels')['default']
    PTabs: typeof import('primevue/tabs')['default']
    PTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    KeyFilter: typeof import('primevue/keyfilter')['default']
  }
}
